### ISSUE TITLE
[ACT][Networkscan][WinPCap] Issue while streaming to youtube with NVidia ShadowPlay

### ISSUE THREAD

**Issue by KarstenS123** [ravahn/FFXIV_ACT_Plugin#105]
[Network_20170807.zip](https://github.com/ravahn/FFXIV_ACT_Plugin/files/1205831/Network_20170807.zip)

ACT is collecting a very huge bloat of data while streaming the footage to youtube with NVidia ShadowPlay.

In the last 2 1/2 hr raid session I got a logfile with a size of more than 1.5 GB.

I've made a little video. At the beginning it shows how the log fills while I stream and the I stop streaming. At the end you can see what happens when streaming is off.

https://youtu.be/KbIu_AsXaWc

**Comment by ravahn** [comment]
Apologies for the delay.  From the log, I see that the IP packet header's total length field is 0000 for all of those problematic packets.  This seems to be related to a network card feature called TCP segment offloading.  This speeds up the performance of sending/receiving large packets by moving the processing to the network card, but can omit certain header fields from the packets sent to a raw socket such as the one used by the FFXIV plugin.

Since the FFXIV game uses a small MTU - I think it used to be capped at 1500, although don't quote me on that - it should not be a problem for the plugin to ignore these packets.  So, I've added some code to do just that.  This will be in the next release.

**Comment by KarstenS123** [comment]
Thanks.

I'll give you a respond with the result.

**Comment by KarstenS123** [comment]
Sorry for the late answer. Just checked it right now. The filter seems to work.

Thanks.
