### ISSUE TITLE
Overlay not displaying % HP properly when HP too high and length set to more than 361

### ISSUE THREAD

**Issue by aausername** [ravahn/FFXIV_ACT_Plugin#106]
Hello, I would like to report an issue with the ffxivparsing plugin coming with ACT.

When targetting normal people and the Overlay Bar to a length of more than 361, the bar looks normal, but if you select a target such as current raidbosses with HP way over 1 million, the bar looks like this: http://i.imgur.com/lv9nEsL.png

Some targets such as alexander prime look like they have a solid color bar even when not set, like in the picture above.

I like to replace the games bars completely with ravahns, so seeing this issue resolved would be of great help, at least for me. Thanks for reading.

**Comment by Dyspathy** [comment]
I'm also experiencing this exact issue. Would be nice to see it fixed.

**Comment by rux616** [comment]
I agree, it would be nice to see this one get fixed.

**Comment by ravahn** [comment]
This was an old issue, but I found the problem.  I was correctly storing current & max hp as UINTs, but when calculating the percentage of the overlay bar to fill with a solid color, it stored the result in an int, which for large numbers rolled over to a negative value.  This will be fixed in the next release.
