### ISSUE TITLE
Binary log file format of FFXIV?

### ISSUE THREAD

**Issue by dj-hedgehog** [ravahn/FFXIV_ACT_Plugin#110]
I am trying to create a simple log parser for the Mac version of FFXIV. Running ACT or similar using .Net Core does not to work.

At least I found the location of the log files `/Users/me/Library/Application Support/FINAL FANTASY XIV/p_drive/User/My Documents/My Games/FINAL FANTASY XIV - A Realm Reborn/FFXIV_CHR0123402E92D12342/log`

I put a log in a Hex editor and can identify the text. However can you point me in the right direction what binary format the log files are so I can identify them better?

**Comment by ravahn** [comment]
So, the FFXIV plugin stopped using that log file a long time ago because it is very unreliable.  you may notice that every session restarts at the beginning, and there's not a great way of determining where the end of the active log is located - or at least I never tracked it down.  It also is only written when the buffer reaches its maximum, i think every 1000 lines or so, so there is a big delay.

Here is a reddit post from someone who decoded the log file format - click the picture link to see the structure.
https://www.reddit.com/r/ffxiv/comments/1vey94/binary_file_format_for_combat_logs/
