### ISSUE TITLE
chat log binary data incorrectly encoded when written to log file

### ISSUE THREAD

**Issue by nyanpasudo** [ravahn/FFXIV_ACT_Plugin#119]
an example of this encoding error can be seen with auto translation entries

hex values for auto translate entry **/disappointed** would be `02 2E 05 0A F2 05 10 03`

when that data is written to the log by the plugin, it is written as `02 2E 05 3E EF BF BD 01 EF BF BD 03`

thus rendering it impossible to actually know what the auto translate entry was.

**Comment by ravahn** [comment]
Interesting - when I echo the autotranslate for /disappointed, my hex editor shows the data in memory as: 
`02 2E 05 3E F2 01 C2 03`

and in the log file I see: 
`02 2e 05 3e ef bf bd 01 ef bf bd 03'

So while the original text is different, it is definitely getting mangled.  I'm reading the log data as a byte array from game memory, and then converting to a UTF8 string to simplify writing to a textfile.  I suspect the UTF conversion is doing the mangling.  I'll see what I can do

**Comment by alphaONE2** [comment]
The problem is that `F2 01` and `C2 03` are not valid UTF-8. As soon as the decoder notices that a sequence is invalid it outputs U+FFFD and resets its internal state. The only realistic way to deal with this short of writing a custom decoder, is to locate and preprocess auto-translate sequences into something that *is* valid UTF-8. I had to do something similar to deal with auto-translate phrases in FFXI for Windower. Ultimately I settled on mapping the entire auto-translate byte sequence into the Unicode Private Use Area so that the data could survive round-trip.

**Comment by nyanpasudo** [comment]
I'm open to collaboration, or helping with any testing if needed or desired

**Comment by ravahn** [comment]
This should not be fixed.  The control codes are removed from the chat log lines by parsing the control code lengths and skipping the tags, but leaving the contents.  It seems to be working well now.  There are still single-digit icons remaining, but I am leaving those for now.
