### ISSUE TITLE
Encounters not populating past v1.5.1.10

### ISSUE THREAD

**Issue by tdewey7** [ravahn/FFXIV_ACT_Plugin#128]
Had an issue where no encounter data would populate using plugin v1.6.1.1 and above. It would report a successful connection upon a test and would display things like current HP of target and such. The issue was resolved by reverting to v1.5.1.10. I am running in DX11 on a Windows 10 computer in 64bit with an Intel i7 7th gen and a Nvidia GTX1080 ti.

**Comment by ravahn** [comment]
I'm hearing sporadic reports of this.  I fixed some issues in 1.6.1.3, but it seems there are more.  Can you email me a log file so I can look at what it is detecting from the game?  ravahn (at) hotmail.com.  Also, have you tried manually selecting your local ip address on the ffxiv settings tab?  not the best solution, but if it works it tells me more about where the problem is.

**Comment by ravahn** [comment]
Just released 1.6.1.5 which fixes the autoselection of IP Address when the game connects to localhost.  So, please give that a try when you can, and let me know if it fixes the problem.

**Comment by tdewey7** [comment]
The new release fixes this problem for me indeed. Sorry I was unable to assist you last night in figuring out the problem. Thank you for the speedy response and fix!
