### ISSUE TITLE
After the latest update I get no info on my parser

### ISSUE THREAD

**Issue by Elysiumss** [ravahn/FFXIV_ACT_Plugin#130]
I have the latest ACT and plugin version.. I got an update when I opened ACT today for the FFXIV parse plugin.. I did the update but now I get no info at all no matter what I do.. it was working fine yesterday

Sometimes a get an error connecting to the server or no response.. something like that

**Comment by Elysiumss** [comment]
I get this on the Parser Messages:

ERROR: Referencia a objeto no establecida como instancia de un objeto., STACK=   en FFXIV_ACT_Plugin.Memory.ScanLogBuffer.ParameterizedRun(Object parameter)

**Comment by ravahn** [comment]
Hmm...ScanLogBuffer hasn't changed, so that is odd.  Can you email me a log file to ravahn (at) hotmail.com?  you can find the log files by going to plugins -> FFXIV Settings and clicking the "Open FFXIV Log Folder" button.

**Comment by Elysiumss** [comment]
I get also "Unable to obtain version info from the web" but I don't know if that's ACT or the plugin

**Comment by ravahn** [comment]
Thanks for the log.   First - from the log, I believe I know what the problem with not seeing data is.  I can see that the FFXIV game is connecting to TCP port 443 on the FFXIV Server,  This is unusual, and usually means a program such as BattlePing or some other proxy / vpn is in use.  Earlier today I got another report about BattlePing specifically and just downloaded and fixed the problem with port 443.  So, the next update should fix the issue with no data.

However, for the parser error message, I'm not sure why that is happening.  I do see for 1.5.1.10 that there is no chatlog text at first, but when you switched to 1.6.1.5, it was properly logged.  Then, you switched back to 1.5.1.0 and the chatlog was working again. Maybe it was related to the update process?

the 'Unable to obtain version info from the web' error sometimes occurs because AdvancedCombatTracker.com website throttles downloads heavily with a 12-hour window.  You should be able to update again in 10-12 hours.

If the next version (v1.6.1.6, to be released soon) solves the no-data problem and you don't see the error again, lets just ignore it.

**Comment by Elysiumss** [comment]
I use Battleping actually.. but I tried with BP on and off.. no luck

**Comment by Elysiumss** [comment]
But I didn't close FF XIV after I loged into the game.. I closed BP and opened the parser again.. no data in the parser.. I'll try again later with no BP on FFXIV and try again

**Comment by Justincredible004** [comment]
@Elysiumss  Yes, I was the one having trouble with BP specifically causing my issue but unlike you, I was not getting errors of any kind. I do suggest trying like you said to run FFXIV without opening BP to see if it helps. You would have to close battleping before even launching the game.

@ravahn Thanks for you quick reply and I am glad that the info I sent you was able to help diagnose the problem. I can't thank you enough for your hard work and look forward to the update. Real heros don't always wear capes

**Comment by ravahn** [comment]
Just released 1.6.1.6 - please give it a try and let me know if it solves the BP and non-BP problems.  If not, I'll try something else.  As a side note, I did my own test with BP and closing the BP window did not update the connection - it still went to BP servers.  So, you probably do need to close FFXIV/relaunch it without BP running.

**Comment by Elysiumss** [comment]
I had to open the parser twice the first time and started working.. now it's working fine every time I close it.. I'll keep testing tomorrow and report.. thanks ravahn

**Comment by ajbob** [comment]
@ravahn HAd the same issues with battleping and no info showing up. Recent release 1.6.1.6  has seemed to clear up the issue and works fine (w/ Battleping on)
