### ISSUE TITLE
I have a problem when broadcast to Youtube

### ISSUE THREAD

**Issue by misafortune** [ravahn/FFXIV_ACT_Plugin#134]
I finally found the reason why stoped DPS meter in every raid battles.
I couldn't running ACT with The Unending Coil of Bahamut(Ultimate) even though other battle r no problem.
The reason is broadcast to Youtube using Shadow Play(Geforce experience). also using Win10pcap
It might be packet capture problem. or japanese client problem ?  wakarimasen.
I'm happy if you give me some hints.
anyway I luv this plugin.
Thank you from japan.

**Comment by ravahn** [comment]
Hi, ShadowPlay is a graphics driver feature from Nvidia.  In theory, it should not interfere with network capture or WinPCap, but I haven't tried it myself.  It almost definitely is not related to the Japanese client, that should be the exact same code as the US/EU client, but just uses region-specific files.

Can you tell me what version of the ACT FFXIV Plugin you are using?  If it works in some places, but not others, it may be due to a bug that was previously fixed.  There is also a new fix coming out to resolve the problem when you log out / log in or restart FFXIV.

**Comment by misafortune** [comment]
Thank you for reply 
I was using 1.6.1.6. 

When I use it ,its gonna stop&freeze DPS meter about 15-20sec from start while broadcast.

also I tried 1.6.1.8,
but This version can't run DPS meter  with some error.

FFXIV Process ID > Refresh List.
↓
ERROR:    場所 Machina.RawPCap.Create(UInt32 address)
ERROR: Invalid Line type    場所 Machina.TCPNetworkMonitor.Run()|2065fbb9143814f5a0b7594a354614f4
ERROR:    場所 Machina.RawPCap.Create(UInt32 address)
ERROR: Invalid Line type    場所 Machina.TCPNetworkMonitor.Run()|90f902abd2e9c6af5bdd5f2ba7f5d399

On the other hand
↓
 [Test GameConnection]> Succeeded: All FFXIV memory ~~~~~

SO,
DPS > NG
Hate(EnmityOverlay) > OK

**Comment by misafortune** [comment]
fixed this issue .
If I don't use winpcap checkbox.it's no problem.
thank you
