### ISSUE TITLE
Massive Log File size

### ISSUE THREAD

**Issue by gravesr1993** [ravahn/FFXIV_ACT_Plugin#135]
There were connectivity issues tonight in 3s and exdeath, and I believe it resulted in the log file being the massive size of 3.8 gigs. 
I'm unable to open it without it crashing, and i'm unsure of where I could upload it for you to possibly look at to gain a better idea of what happened if you care.

![unknown](https://user-images.githubusercontent.com/10466347/32533436-e7919338-c40d-11e7-9d49-195034d53e78.png)

**Comment by Squall-Leonhart** [comment]
notepad++ will be able to open the file properly, notepad will try and load it all in one go and crash.

**Comment by ravahn** [comment]
This seems terribly large...What might have happened is that TCP retransmitted packets were stored fully intact in the log file by my new network code.  I just went through and updated all the places which log network data due to error conditions to only include 30-50 bytes, and I disabled logging TCP retransmissions completely.  Apologies for the large file, if you cant open it feel free to delete it!

Let me know if the problem happens again after the next version of the plugin is released.

**Comment by gravesr1993** [comment]
It's actually too big to be opened in notepad++ as well haha!
Thanks for the quick response, i'll definitely let you know if I see it
happening again

**Comment by gravesr1993** [comment]
![image](https://user-images.githubusercontent.com/10466347/33921596-185e79ce-df82-11e7-8ec0-6ba44d4c262b.png)

the issues seems to be happening again, there were times of 3-5 minutes where the game would stop receiving inputs however I could still output data to the server and have it register as well

**Comment by Blade2187** [comment]
I'm experiencing the same issue. ACT was working perfectly for me until around... October/November maybe?... when I started sometimes getting this exact sort of error. The overlay stops working (RainbowMage plugin or some fork of it), the data stops updating in the main ACT window I think, frames get dropped, and I have to close ACT and delete the multi-gig logfile because it's just full of lines of the above error (FFXIVBundleDecoder: unknown encoding type). Those errors are usually preceded by a couple lines saying something about receiving TCP packets in an unexpected order.

I'm on a Wifi connection (wired not possible ATM) and the network is set to private. I'm using Win10 Pro without any third party firewall/antivirus software. ACT and FFXIV are both "allowed" for private networks in the Windows Firewall settings. ACT x64 is running as admin. I'm on a fairly new Optimus laptop, if that matters for anything.

I tried setting the IP to my local IP (assigned by NAT router) specifically; the dropdown list also listed a loopback IP. At first that seemed to help but the problem cropped up again halfway through Rabanastre. (During the chocobo/mimic part I believe; I imagine there is extremely heavy load there due to 24 people spamming AOEs on 8+ targets.)

I also just now downloaded Win10Pcap and checked the box for ACT; will update if that seems to help next time I play.

**Comment by ravahn** [comment]
I have found a bug which might help resolve this problem.  When there is significant network load on the local machine (ex - large file copies, etc), data is lost.  I am experimenting with work-arounds.

I also have a fix for the log filling up due to encoding type messages.  

It will take a few days to finish this up and release it.
