### ISSUE TITLE
Wildfire is not registered.

### ISSUE THREAD

**Issue by AzuronBurrito** [ravahn/FFXIV_ACT_Plugin#149]
I have encountered a problem regarding wildfire today. I've been progging O8S today for two lockouts and everything seemed fine until my wildfire wasnt registered anymore for some reason.

I only have a suspicion as to why that is. On the Kefka kill in the 2nd lockout my wildfire ended pretty much after or at the same time as the boss became untargetable. Maybe ACT "thought" wildfire was still going.

For testing purposes i reopened act and it registered wildfire again. So it seems my suspicion goes into the right direction.

**Comment by ravahn** [comment]
I received another report on this and you are right - Wildfire does not register in situations where it should.  I believe I tracked it down to two different issues - one is a problem where there was no default Wildfire debuff duration, so the internal tracking for the final Wildfire damage was getting confused.  This appears to be the primary problem, and I have a potential fix ready to go out soon.

There is a secondary problem where trying to parse a non-US-localized logfile that uses commas as the decimal separator on a US-localized PC causes the durations to all be multiplied by 100 - i.e. 1,50 is interpreted as 150, not 1.50.  I'm working on a complete code review to fix this so that it uses region-independent formatting for all decimals and integers when formatting strings, but this is going to take some time.

**Comment by ravahn** [comment]
This should be fixed now with the latest 1.7.0.9 release.
