### ISSUE TITLE
BLM dps extremely inaccurate

### ISSUE THREAD

**Issue by MollyYubi** [ravahn/FFXIV_ACT_Plugin#155]
I've been using ACT for a long time and was always forced to use memory parsing due to internet issues which cannot be addressed, however since 4.2, parsing as a black mage has been extremely inaccurate, losing between 1000 - 3000 dps on dummy parses and between 1000 - 1500 in raid situations. Currently I can't go over 3500 dps on a dummy parse as a black mage with high item level gear, while before on a dummy I was parsing 5.1 k + dps locally. This only happens for BLM, all other jobs are fairly accurate, as much as memory parsing can be.

**Comment by ravahn** [comment]
I do suggest trying WinPCap (http://www.win10pcap.org/)  as a solution to the internet issues you experience, it frequently solves a lot of problems, but I imagine there are probably some which cannot be solved.  That's why I leave memory parsing enabled, even though it is inaccurate.

The primary source of parsing inaccuracy is due to the DoT simulation.  Since around patch 4.0, SE moved certain buff effects from in-game buff icons onto the gauge system.  Unfortunately, their network traffic does not communicate this gauge data for other players except to a very limited extent, making it impossible to use it and have any sort of parse accuracy at all.  BLMs in particular are affected by this problem.  I'm working on a fix that would apply to both memory and network parsing, but it is going to take some time.

**Comment by ravahn** [comment]
This should be significantly improved after the DoT improvements in Dec/Jan.
