### ISSUE TITLE
No parsing data

### ISSUE THREAD

**Issue by TalakinRaclaw** [ravahn/FFXIV_ACT_Plugin#169]
I updated ACT after FF14 4.3 patch dropped and it worked for a day but now it only shows me what area I am in.  It is as if it's waiting for data.  Other players I've spoken with say it's working without an issue.  Any advice will help.

**Comment by VAshford** [comment]
I'm having the same issue now myself. It's strange though because before these last emergency maintenances it'd work fine, but now it doesn't. I understand these files probably need updates after patches but what's even stranger to me still is that some people in my raid are using it without a problem? I'm not..entirely sure what's happening.

**Comment by aaltayeb** [comment]
I saw this happens when either ACT wasn't lunch with "Run as administrator" or it wasn't allowed in windows firewall.

**Comment by TalakinRaclaw** [comment]
Which it was under administrator and with the firewall offline.

**Comment by chanzie** [comment]
yea mine was working fine pre patch and after update all im getting is blank checked firewall, checked all settings removed all additional plug ins etc still cant get any data to view

**Comment by ravahn** [comment]
Assuming there wasnt another FFXIV patch at the time, the most likely cause is that windows firewall got confused after a system update and the firewall rule is no longer working.  Solution is to remove the firewall rule and re-add it back.

This also can be caused by FFXIV patching itself, in which case you would just need to close and reopen FFXIV.  If the problem persists, one solution is to install WinPCap and configure the Parse Settings for the plugin to use it.
