### ISSUE TITLE
Text To Speech not working

### ISSUE THREAD

**Issue by Taisaku101** [ravahn/FFXIV_ACT_Plugin#189]
I have been using ACT in FFXIV for parsing and voice prompts (TTS) with triggers since around Stormblood release. After the most recent patch 4.4 none of my tts triggers work. The timer is working properly and does show the countdown and the placement for tts to go off properly but the tts will not work. Is this a known issue or do I need to change settings/edit my triggers? Thank you for putting so much work into ACT, IT IS AMAZING!!!

**Comment by szalkerous** [comment]
I can confidently say that my TTS for hunts were working 100% yesterday after the latest plugin update (using ACT built-in trigger parsing with TTS).

That being said, every config is different. I would pop over to the ACT forums and ask there, it sounds like a general ACT config issue.

**Comment by jas612** [comment]
I had this same problem.  After the plugin update, it just so happened that ACT also hadn't updated in a while, and updated.  When it did, it changed my Options -> Sound Settings from "Use Windows API Sound" to "Use WMP API Sound".  The latter does not work for me because I do not have Windows Media Player installed.  The former works for me now.

Either way, I do not think this at all related to this plugin:  it's presenting a valid combat log back to ACT, so its job is done.

Hopefully this helps!
