### ISSUE TITLE
Potential incorrect potencies?

### ISSUE THREAD

**Issue by dejesusg** [ravahn/FFXIV_ACT_Plugin#190]
Line 70693 of the DLL has:
```
 <job id="19" name="black mage" damagetype="magic">
    <ability id="df9" name="fire iv">
      <damage potency="300" />
    </ability>
  </job>
```

BUT

Line 70898 has:
```
  <job id="19" name="black mage" damagetype="magic">
    <ability id="df9" name="fire iv">
      <damage potency="280" />
    </ability>
  </job>
```

looks like you might have updated the potency in one spot but not another or are overriding the value later on incorrectly.

There are also other instances I found where this also occurs.

**Comment by jas612** [comment]
I don't know for sure, but I remember something from a long post ago that each patch is simply adding new sections to calculate potency as they arise, and some of the old patches' data is still resident.  Against which it is calculating though is relevant, so color me curious

**Comment by ravahn** [comment]
Yes, the ACT Plugin embeds information about multiple patch versions and the potencies from that version, to allow for some degree of accuracy when importing older log files.  Unfortunately due to other structure changes it breaks when there are major (3.0, 4.0, etc) game changes, but in general it is reasonably accurate back to the last major version.  So, what you are seeing are the incremental potency changes for fire iv from different ffxiv patches.   

If I recall correctly, It determines the correct patch data to use by looking at the first line's timestamp in the log file, and using an internal structure to determine the patch # that corresponds with that log file.
