### ISSUE TITLE
Changing active encounter to selected

### ISSUE THREAD

**Issue by Mephi-Dross** [ravahn/FFXIV_ACT_Plugin#20]
I'm not sure if this falls under your job or it's ACTs job, so feel free to close/delete if it's nothing you can do about.

Would it be possible to change the active encounter to the one you have currently selected in ACT? 
It would be nice to have for e.g. RainbowMages OverlayPlugin, since you can switch through fights and see the info you want without having to manually search through ACT.

**Comment by ravahn** [comment]
This is probably something that would have to be changed in the OverlayPlugin, not ACT or the FFXIV plugin.

Browsing quickly through the OverlayPlugin code it seems to be using the following reference for encounter data:
ActGlobals.oFormActMain.ActiveZone.ActiveEncounter

instead of using ActiveEncounter, OverlayPlugin could access the ACT main treeview via this property:
ActGlobals.oFormActMain.MainTreeView
and use that to determine which zone and encounter node are selected.  I assume there is some sort of identifier in there, such as the ACT encounter ID.  If so, that can be used to find the specific encounter in the ActGlobals.oFormActMain.ZoneList array.  There may be better ways of doing it, but that should work as a first attempt.

I recommend you get in touch with RainbowMage and submit this as a feature request, I am sure other people would find it useful.

**Comment by Mephi-Dross** [comment]
I see, thanks for the answer! Must have missed that line of code and it seems bloody obvious now. Will do that.
