### ISSUE TITLE
Improvement ideas for overlays

### ISSUE THREAD

**Issue by haasn** [ravahn/FFXIV_ACT_Plugin#207]
I think the overlays feature is extremely useful. In particular, it allows me to hide the clunky and awful default target bar completely and use this overlay instead. That being said, I think there are a lot of ways they could be made better. Here are a couple of suggestions:

- Allow adding overlays for player resources (life, mana, tp)
- Instead of using the same color for the entire "color bucket", blend between the starting and stopping colors. That way we could make (multi-segmented) "gradients" of color. (Bonus points: Please convert the colors to linear light when blending!)
- For HP bars, allow customizing the bar based on the class/job of the target. This goes in line with how most other MMORPGs handle bars, which is IMO much more useful than just showing a green bar for everything.
- Allow adding party/alliance bars. These should ideally be roughly laid out the same way as the ingame party/raid bars, so we can just put them "on top" of the ingame ones (and make those have transparency 90%).

In general, I think we should strive towards making a complete "UI replacement" that replaces as much of the horrible default UI by something closer to what ElvUI and friends do for WoW.

Anyway, thanks for the great work. The new target bar alone makes this game *much* more playable!

**Comment by ravahn** [comment]
These are excellent ideas.  These overlays were very simple additions I made early on with the plugin, back when FFXIV didn't include target hit points at all, and players wanted a way to determine transition points for encounters - i.e. 80%, 50%, etc.  Since then, various expansions and patches have added both target hp and also target hp %, so the original purpose of these overlays is gone.

I'd like to focus on the data collection and parsing functionality of the FFXIV Plugin, rather than add additional UI and enhancement features.  It's more than enough work just handling the patch changes and trying to improve DoT simulation accuracy.   I've considered retiring the overlays completely, but since there isnt anything out there yet to replace it, I've left them.  Hopefully another developer would be willing to step in and create their own target overlay plugin.  Player and mob targets can be read through the FFXIV_ACT_Plugin.Common.IDataRepository interface now, so all the necessary memory information is available with no need to write custom memory reading code.

**Comment by ngld** [comment]
FWIW it should be fairly simple to do this with OverlayPlugin and Cactbot. Cactbot already provides a lot of data and rendering that in OverlayPlugin is very simple. If any of the information necessary isn't exposed via OverlayPlugin, yet, it should be fairly simple to write an addon to solve that.
