### ISSUE TITLE
ACT keeps saying new version is available (1.7.2.6)

### ISSUE THREAD

**Issue by stinkpalmd** [ravahn/FFXIV_ACT_Plugin#208]
I have installed the latest release (1.7.2.6) on two different machines and both keep saying there is a new release of the parsing plugin whenever I launch ACT. If I say "yes" to updating, my parser appears to not work. If I say "no", everything works just fine.

**Comment by aklein13** [comment]
@stinkpalmd 
I've had the same issue on 1.7.2.6 and 1.7.2.8.
The part of it is version check (1.7.2.8 is the newest so it shouldn't ask to update, right?) and the part other part of this is on windows permissions...

I manged to solve that with the following steps:
1. Copy ACT folder to another drive (another location on the same drive should be fine as well. I just moved it out of the system drive to make sure it works this time).
2. Run it and click "yes" to the update prompt. Now it should update itself (to the same version tho).
3. Now you can either close this duplicated version and delete it (the old version won't ask to update) or you can keep using it as you'll propably face the same issue with every next version due to windows being windows.

**Comment by Lifell** [comment]
I've got this problem on 1.7.2.8 as well. Setting all users to "Full Control" permissions has no effect. Running the .exe as administrator has no effect. What is this?

**Comment by stinkpalmd** [comment]
@aklein13 your steps of launching a copied instance of the program worked for me. no longer prompting me. thanks for the fix!

**Comment by Lifell** [comment]
Wouldn't really consider that a fix considering the next update you will very likely have the same problem. It's a nice workaround for now though.

**Comment by Lifell** [comment]
This hasn't been fixed yet and I think I will lose a lot of my settings if I use the steps "aklein13" used. I also don't have ACT installed in any of my program files folders so this shouldn't even be an issue.

**Comment by aklein13** [comment]
@Lifell I didn't loose any of my settings and all you do is just running it from the other location so it shouldn't break anything. Although they are stored at `C:\Users\<Your user name>\AppData\Roaming\Advanced Combat Tracker` so you can always do a backup.

**Comment by Lifell** [comment]
Ah right, the settings are stored elsewhere and still lead to the old installation. So in that sense I could download a fresh copy of ACT and just put it on my desktop, run it to "update" the plugin, close it and delete the desktop version.

Makes sense, thanks for your reply!

**Comment by dans74777** [comment]
I clicked yes on the update now my plugin is not working, is there any way to undo that? I can’t figure out what’s up because my act is still working, just my plugin is not. Thanks

**Comment by ravahn** [comment]
Thanks to Aditu (ACT author), I've made a significant change to how the version check works with 2.0 and greater version of the plugin.  Instead of looking at timestamps, it looks at a version textfile on the server, and compares the running plugin version to this remote version number.  This should eliminate the problems you experienced with the previous date-based version check.
