### ISSUE TITLE
No data in ACT's "Main" window

### ISSUE THREAD

**Issue by annabunches** [ravahn/FFXIV_ACT_Plugin#21]
I'm using ACT with the FF XIV plugin, but the "Main" window never seems to show me any data. I did a test-run through a dungeon, and nothing appeared there either during or after. The name of the current zone shows up correctly, but no combat data ever appears.

There is nothing under "Parser Messages", I've already encountered and fixed the standard networking and admin privilege issues.

The plugin's log files are full of what looks like sensible combat data. If I go to the History Database and search over the day, it even shows the dungeon run. Sometimes hitting 'import' on that zone seems to work without issue. Other times it throws an error: "Could not find a log file for your character that likely had the date range. Please find this file." Then a file chooser opens, I pick the presumably correct file, and the "Import" dialog appears and seems to work. But still nothing back in the Main window. :(

Using the "Import a Log File" option has similar results.

Every indication I see suggests this should just work "out of the box". Any ideas what's wrong?

Another troubleshooting step I tried, that also failed: deleting the entire Advanced Combat Tracker config directory (under AppData/Roaming/) except the FFXIV Logs, then importing them from a pristine config. Same behavior.

(Windows 8.1, incidentally)

**Comment by annabunches** [comment]
Additional note: If I import data from the history database, and go back to the main window, the left-hand navigation tree is gone. If I click the back arrow / up to parent node button on the top-right pane, ACT throws an exception (although Windows happily allows me to keep running the program. Non-caught non-fatal exceptions strike me as strange. But I do all my programming in Linux.)

Anyway, stack trace / whatever data Windows spits out in this instance is included here:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Advanced_Combat_Tracker.FormActMain.btnNavBack_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34014 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Advanced Combat Tracker
    Assembly Version: 3.2.0.250
    Win32 Version: 3.2.0.250
    CodeBase: file:///C:/Secondary/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34250 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
GammaJul.LgLcd
    Assembly Version: 1.1.3.0
    Win32 Version: 1.1.3.0
    CodeBase: file:///c:/secondary/advanced%20combat%20tracker/GammaJul.LgLcd.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.85.5.452
    Win32 Version: 0.85.5.452
    CodeBase: file:///c:/secondary/advanced%20combat%20tracker/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
FFXIV_ACT_Plugin
    Assembly Version: 1.3.0.16
    Win32 Version: 3.2.0.250
    CodeBase: file:///C:/Secondary/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ravahn** [comment]
It sounds like network parsing is enabled, but none of the data is being received by the plugin.  Finding the cause of this can be tricky, since you've already addressed Windows Firewall and Admin permissions.  

Just to be sure it isn't an OS incompatibility, I installed windows 8.1 in a virtual machine, installed ACT, added firewall rule, updated DirectX, installed FFXIV, patched FFXIV, and ran ACT+FFXIV.  I successfully saw combat data when attacking a training dummy.

The error you get when importing HistoryDB sounds like it may be due to importing from a file with no combat data, so I would put that aside for now.  

Focusing on the lack of combat data in ACT, here's some things to look at:
* Did you change the option on Plugins -> FFXIV settings for "Local IP Address" from the default value? if so, change it back to "All (Default)", just in case.  Deleting the config file might have already done this.

* Are you using any other type of firewall software or internet protection on your PC? if so, temporarily try disabling it.  

* Are you using WTFast, Pingzapper, or any other VPN / tunneling software?  If so, try without them to eliminate problems

* Do you happen to have VirtualBox installed? I believe that it installs a kernel driver that can interfere with network packet capturing.

If none of the above helps, can you email me a log file where you attack a training dummy to ravahn (at) hotmail.com?  I'll take a look to see if there is anything helpful in there.  Even better if you turn on the "(DEBUG) Dump all Network Data to logfile" option, but dont run with that on for more than a minute or two, since it may produce huge log files.

As a last resort, if you disable network parsing (Plugins -> FFXIV Settings, "Disable Parsing from Network Data" checkbox), it should read data - however it will be slightly less accurate under high-load situations.

**Comment by annabunches** [comment]
Thanks for the detailed response! I'd be surprised if the issue was that it's not getting combat data, because I see things like this in the log files:

00|2015-05-21T19:17:21.0000000-04:00|082b||You cast Stone.
00|2015-05-21T19:17:21.0000000-04:00|0aa9||   The fleshfly swarm takes 43 damage.
00|2015-05-21T19:17:21.0000000-04:00|0aaf||   The fleshfly swarm suffers the effect of Heavy.


In terms of your bullets:

* I changed the setting at one point to exclude localhost, just to see if that mattered, but only for one test. It's been at the default most of the time.
* No firewalls or anything similar going on.
* No VPNs or anything like that. Nice, boring network topology with a home gigabit router plugged into a cable modem. Network has 2 Windows PCs, a Linux server, and a variety of laptops and phones and such. My housemate, on the same network, runs FF XIV + ACT with no problem.
* No VirtualBox, no virtualization of any sort going on.

I will happily send you a log file.

**Comment by annabunches** [comment]
Ok, sending logs to you. Interestingly, the ACT overlay *works* while I'm in combat, but no encounter data ever shows up.

**Comment by annabunches** [comment]
I turned off Network Parsing and it worked *immediately*. I don't get how that makes any sense, given that I saw what looked to me like combat data in the log files. And I'd rather have network parsing working, at any rate.

**Comment by ravahn** [comment]
I'm working on an alternate form of network parsing that uses the free WinPCap software instead of my own network routines.  I had it basically working pre-3.0, but need to do more extensive testing and add UI features to enable it before I release it to the public.

Would you be willing to use the WinPCap driver in conjunction with ACT? It requires a separate download & install here:
http://www.winpcap.org/install/default.htm

**Comment by annabunches** [comment]
Blah, github failed to deliver this message. Answer: sure! Always happy to help test things. I'll install it next time I'm at my gaming machine. Just let me know how to get a version of the plugin that works with the driver.

**Comment by fnietzsche** [comment]
Ravahn, first, thanks for creating this plugin, so awesome. I know this is an old response, but I'm having a very similar issue. ACT and plugin work as long as I 'disable parsing from network data'. The problem is... I'm trying to make it compatible with FF Logs, which in the setup video states to never check this box. FF Logs seems to uploads the files, but no data appears. I've tried with the box checked/unchecked, with no luck. Anyone having a similar problem or solution? Thanks

**Comment by Gallagos** [comment]
Hey guys, just wanted to comment saying I was experiencing the same affect; damage & interactions were showing up in the ACT log, but not in the mini-viewer, or parse windows.  Disabled Network Parsing and it worked immediately.  I'll try with the WinPCap driver next.

**Comment by klessel** [comment]
Thank you Ravahn!  Installing WinPcap for Windows 10 worked for me.  You can find it here:
http://www.win10pcap.org/download/   Just install it and then in ACT select the checkbox for 'Use WinPCap Network Driver' under 'Plugins' and 'FFXIV Settings'.

**Comment by wmollenkopf** [comment]
> 
> 
> Thank you Ravahn! Installing WinPcap for Windows 10 worked for me. You can find it here:
> http://www.win10pcap.org/download/ Just install it and then in ACT select the checkbox for 'Use WinPCap Network Driver' under 'Plugins' and 'FFXIV Settings'.

Just wanted to also chime in that this worked as well for me. I've been turning off firewalls, etc, etc. Probably was/is battle ping that has been giving me issues -- but the WinPCap saved me. Woo thank you! Hopefully the comment will help others in the future as well (or me when I forget that I did this to solve my troubles later on)
