### ISSUE TITLE
ACT confusing two players

### ISSUE THREAD

**Issue by quisquous** [ravahn/FFXIV_ACT_Plugin#212]
In https://github.com/quisquous/cactbot/issues/392 somebody reported that they were getting dps updates and callouts as if they were somebody else.  It's very possible that this is a cactbot problem (some weird memory thing sending the player name as something else), but there's two suspicious things on the ffxiv plugin or even ACT itself end of things.

(1) for dps output, cactbot uses ActGlobals.oFormActMain.ActiveZone.ActiveEncounter.GetAllies() as the allies which also confused the sch and the smn.  It doesn't process any of the names there, so YOU was wrong somehow.

(2) when importing the log from the above cactbot issues link, the smn is listed as a sch as their job type in hydatos, even though I verified from logs that they were a smn the whole time.

**Comment by ravahn** [comment]
Sorry for the delay, but I did find some information as to the reason ACT got confused.  When changing zones, ACT logs the identity of the parsing player in order to determine who 'you' are.  It finds this identity by looking at the array of combatants and picking the first one.  I've never seen this before, but for some reason it is picking the wrong identity - here's the log line:
`02|2019-03-21T22:08:19.3710000+01:00|1067e19b|Kioki Kun|ec7e568fb981099f19462bbbcb733564`

Everything else is likely a cascading result of this problem - if ACT doesn't know who 'you' are accurately, triggers probably wont work, and the overlays wont show the right information.  However, since this is the first time I've encountered this problem, it seems to be incredibly rare.  I'm going to reflect on whether I can improve detection of 'You' when 5.0 comes out.  It may require a new memloc.

**Comment by ravahn** [comment]
To follow up on this, 5.0 didnt radically change the array of combatant pointers, but I did completely re-write how this array and all the combatant data are read in the 2.0+ line of FFXIV plugin.  Have you heard of this issue continuing to happen?

**Comment by quisquous** [comment]
No, this one instance was the only time that I've heard of this.  I'll close this for now and can reopen it if I ever hear of it again.
