### ISSUE TITLE
Parse network from PS4 connected via bridge to a PC?

### ISSUE THREAD

**Issue by ghost** [ravahn/FFXIV_ACT_Plugin#216]
Is it technically possible to intercept network packets sent from and to a PS4 if you connect it via LAN to your pc and make a new bridge connection with an already existing network adapter? Or maybe the complete lack of a log file makes this whole idea useless?  
Sorry if I'm saying nonsense here, but I thought that maybe this is the best place to ask

Source: https://www.thetechgame.com/Tutorials/id=20329/how-to-directly-connect-your-ps4-to-your-pc-via-lan-cable.html

**Comment by ravahn** [comment]
This is a good idea, but I haven't pursued it because the plugin needs to combine both network data and memory data.   It may some day be an additional feature - to support 'network only' parsing - but it will have limitations, such as the player must open ACT before zoning into an instance, or before logging into the game.  

The good news is that the FFXIV log file is not used by the plugin at all, so it won't be a problem.
