### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by mute55** [ravahn/FFXIV_ACT_Plugin#231]
Hi, 

I'm trying to get the FFXIV ACT Plugin working in Linux, as I use it as my main OS and play FFXIV.
I've managed to get ACT working fine, however the plugin dies due to an error with TinyIoC.
Is there any chance of removing TinyIoC from this project? Or open-sourcing it, so that I can convert it to dotnet core and remove the need for TinyIoC? I see no reason for this project to be kept closed-source.

**Comment by ravahn** [comment]
TinyIoC is already open source here: 
https://github.com/grumpydev/TinyIoC

I referenced it from Nuget in my project.  I'm open to an alternative IOC container, but this one was particularly useful because it doesn't require a separate DLL, it allows for simple scope definitions (singleton vs instanced), and allows for both interface and class resolution.  I don't think I've made any changes to TinyIoC source code after adding it to the project from Nuget.

Regarding running in Linux, the network packet reading might work via winpcap (someone tried to get that working and partly did), but I would be surprised if the plugin's ReadProcessMemory calls work for interprocess communication.  However, I haven't tested.

The plugin is not going to become open source, although I may make portions of the source code public  in the future.  It is not obfuscated c# code, so even today it should provide enough transparency for interested developers to review and verify that it is safe and not sending data to third parties, or accessing local files improperly.

**Comment by mute55** [comment]
> The plugin is not going to become open source, although I may make portions of the source code public in the future. It is not obfuscated c# code, so even today it should provide enough transparency for interested developers to review and verify that it is safe and not sending data to third parties, or accessing local files improperly.

Why?

**Comment by mute55** [comment]
@ravahn
