### ISSUE TITLE
Plugin startup failed.

### ISSUE THREAD

**Issue by Neptisg** [ravahn/FFXIV_ACT_Plugin#238]
Everything was fine yesterday. Suddenly got this error today. (see image)
![J0xQxX8](https://user-images.githubusercontent.com/55879779/65765509-bac62500-e128-11e9-9b75-f70eed423b04.png)

**Comment by Badermachine** [comment]
i have the same problem did u manage to fix it ?

**Comment by Neptisg** [comment]
reinstall ACT completely.

**Comment by EQAditu** [comment]
The actual issue is that the plugin config file has data in it that it can't understand. Deleting it or otherwise fixing said config file would be a more direct fix for the issue. *Usually* this kind of issue is caused by the user changing regions in the OS in a way that uses different numerical delimiters... but that usually has a slightly different message.
