### ISSUE TITLE
Seems to be quite broken with the June 25th hotfixes.

### ISSUE THREAD

**Issue by Squall-Leonhart** [ravahn/FFXIV_ACT_Plugin#24]
Within a few seconds of starting an encounter, a new one will begin, DPS values become 0 and an error appears in the graph box.

Attempting to toggle network data parsing will cause an object state error

This error also pops up when you close ACT.

**Comment by ravahn** [comment]
Just released v1.4.0.6 to fix this problem.  The latest patch broke one of the memory signatures used to measure the timestamp when an event occurs. 

Rather than use the pc's local time, the plugin pulls the time from game memory.  This is to help correlate with the chatlog buffer timestamps, which could be sitting there for a long time if you load ACT after being in game for a long time.

**Comment by Squall-Leonhart** [comment]
Ah, dang, 3.01 reintroduced this.

**Comment by ravahn** [comment]
Hmm. can you confirm?  I tested dx9 and dx11 and only the dx11 chatlog signature seemed broken.

**Comment by Squall-Leonhart** [comment]
Oh, hmm seems it is just the signature,  i was trying to get a reading from ACT earlier after patch and the results from a striking dummy weren't consistent,  thinking back i might not have closed ACT during the downtime.

**Comment by ravahn** [comment]
Sounds good, glad it is not still a problem!
