### ISSUE TITLE
Patch 5.15 breaks plugin

### ISSUE THREAD

**Issue by glaap** [ravahn/FFXIV_ACT_Plugin#243]
Since the update to ffxiv no damage is being parsed anymore.
The game is still recognized in the Game Connection Test.

**Comment by EQAditu** [comment]
FYI, every trivial patch that updates the game client will cause this. It is a known issue and reporting a break every minor patch will be unnecessary. Because this patch is trivial, the memory locations are unchanged and the game test passes. The network part is what changes, which changes in a minimal but important way.

**Comment by ravahn** [comment]
Aditu is right, and to close the loop, version 2.0.4.6 with fixes to support 5.15 is now released to the auto-updater, so closing this.
