### ISSUE TITLE
why source code is not public?

### ISSUE THREAD

**Issue by ChoppinBlockParty** [ravahn/FFXIV_ACT_Plugin#245]
I am just wondering what is a blocker for publishing the source code, unless you want to earn money selling it, but probably would be more profitable to open source of it and ask for donations. You might get many improvements, mb even from the square enix development)).

**Comment by tant4lus** [comment]
Or maybe SE will find a way to shut it down when it knows how the plugin is getting the data? They haven't really been for parsing and turning a blind eye to people using it.  If SE wanted to implement a parser, they could have done that ages ago.

**Comment by ravahn** [comment]
It is not public because running an open source project requires more effort to coordinate and maintain distributed individuals who may or may not be available to rely on when portions of the combined project break with game changes/updates.   I see no reason to change this. If I decide to stop supporting the plugin, then I will likely open source it rather than abandon it, but I am not aware of a good reason to do this for now.  

I do not accept money for the work to create or maintain the plugin.  Instead, I recommend donating to Advanced Combat Tracker and to FFLogs to support those projects if you find them useful.  My motivation for creating this plugin was first for personal use, and later as a benefit to the community.  Since I stopped playing FFXIV a number of years ago, I continue to maintain the DLL for that reason, but also to explore the coding challenges in a project that combines multiple realtime data streams and provides useful information out of them.

Regarding contributors, there are a lot of great programmers and reverse engineers out there.  I speak with a number of them on discord regularly.  But, it is a whole different thing when people want to submit changes.  Often they are good ideas - fixing bugs, cleaning up rough spots, etc.  Sometimes they will be very bad ideas, though - adding new layers of processing, accessing new data which is hard to maintain,  For this reason, most developers will build their own DLLs that run on top of mine inside ACT, and this has worked out very well.  My DLL exposes sufficient information to access game memory and network data efficiently, and thus the core DLL remains more stable.  If there are additional general-purpose hooks needed, I'm open to adding them, I can be found on Discord.  Running an open source project has overhead in order to reduce the friction when changes need to be revise, or a rejected.  I would prefer to spend my time on other things.
