### ISSUE TITLE
Machinist's skill Wildfire isn't calculated 

### ISSUE THREAD

**Issue by essencious** [ravahn/FFXIV_ACT_Plugin#25]
The plugin doesn't seem to be counting the initial damage or the burst damage at the end of the wildfire debuff.

It's making the machinist look like it's doing really low DPS :(

**Comment by ravahn** [comment]
According to xivdb Wildfire does not have an initial damage.  Is this incorrect?
http://xivdb.com/?skill/2878/Wildfire

Regarding the burst damage at the end, it should work in Network Parse mode (i.e. uncheck the "Disable Parsing from Network Data" checkbox).  It will take a while to get it working for memory mode - I spent a while debugging it the other night but could not find the buff ID in game memory.  

If you cannot get Network mode to work, once things slow down from the patch, I plan to introduce a new feature where the plugin will use the freely-available WinPcap software to read network data, instead of my own code.  This may help some people who just cannot get it to work.

**Comment by Rami2010** [comment]
i tried Wildfire last night with Network mode and still doesnt show wildfire damage at all

**Comment by ravahn** [comment]
Can you email me the logs from last night - ravahn (at) hotmail.com?

**Comment by Rami2010** [comment]
it seems wildfire show up seems i had brain issues yesterday really sorry :D

**Comment by ravahn** [comment]
Great! It will work inconsistently, if at all, in memory mode because there is no fixed potency so it isnt possible to differentiate between a regular DoT and wildfire damage.  In network mode, the buff ID is sent with Wildfire so it can be parsed.

Since I have no way to fix this in Memory mode, I'll close it.
