### ISSUE TITLE
Delubrum Reginae Boss "Trinity Avowed" Attack counting as damage out for players.

### ISSUE THREAD

**Issue by Nyghts** [ravahn/FFXIV_ACT_Plugin#262]
The effect "Cold Shock" and "Heat Shock" which occurs when the player fails a mechanic deals 9,999,999 damage to the player, it seems to be copying the damage as outgoing damage for the player as well as incoming damage.

![Bugged Outgoing](https://user-images.githubusercontent.com/6118392/107326792-a6f73680-6a71-11eb-9546-d4b4016bbb0f.png)

**Comment by EQAditu** [comment]
The game servers are saying the player is casting it on themselves, so that's what the FFXIV parser is saying.
Ravahn is already considering a hard-coded exception to fix this behavior.

If you really want it gone now, before a plugin update, copy the following then click **Import XML** button on the corner of ACT:
```xml
<Config Xml="&lt;AbilityRedirectFix&gt;&lt;Redirect Active=&quot;True&quot; Ability=&quot;Cold Shock&quot; Into=&quot;Trinity Avowed&quot; Type=&quot;1&quot; /&gt;&lt;Redirect Active=&quot;True&quot; Ability=&quot;Heat Shock&quot; Into=&quot;Trinity Avowed&quot; Type=&quot;1&quot; /&gt;&lt;/AbilityRedirectFix&gt;" />
```
