### ISSUE TITLE
Can't get act to show any informations

### ISSUE THREAD

**Issue by Deenosaurus** [ravahn/FFXIV_ACT_Plugin#278]
Hey, since the new update ACT won't get any information in the main tab. Location of the log files are right, I can also see it jumping in lines. It also shows where I'm currently ad, just no damage.

**Comment by insomnolence** [comment]
A new version of the plugin is needed for any patch/update/expansion. Usually it is released the same day, but may vary due to the author's time and time zone. You can be notified of releases by selecting the watch dropdown ( above right in github), select custom, and check releases box.

If you don't want to be notified via that method, you can simply load ACT randomly throughout the day to see when the update is ready.

**Comment by Deenosaurus** [comment]
> A new version of the plugin is needed for any patch/update/expansion. Usually it is released the same day, but may vary due to the author's time and time zone. You can be notified of releases by selecting the watch dropdown ( above right in github), select custom, and check releases box.
> 
> If you don't want to be notified via that method, you can simply load ACT randomly throughout the day to see when the update is ready.

Thanks! I didn't knew if there was already a new updated, cause I haven't used ACT since DLC Release and it updated a bunch. Ty for the quick reply!
