### ISSUE TITLE
Every time I attack it makes a new target

### ISSUE THREAD

**Issue by Corrupt1on** [ravahn/FFXIV_ACT_Plugin#29]
Every time I use an ability on a striking dummy it creates a new target. I cannot track all damage together. Happened with most recent update, I don't know if its a bug or not so Ill report it anyway.

http://prntscr.com/7oe066

**Comment by ravahn** [comment]
/u/GBraver on Reddit suggested this might be due to a beta version of the Guildwork client injecting the wrong timestamp into the chatlog buffer.  Are you using Guildwork?

If so, and you do not have Network mode of the ACT plugin disabled, you may be able to work around this problem.  Go to Plugins -> FFXIV settings and check the box "Disable Combat Log (reduces file size)".  This should prevent the memory scanning portion of the plugin from logging any events from the combat log, and thus the invalid timestamps will not affect it.

If you are not using the plugin, can you make sure your PC is correctly synchronized with a time server - click the date/time in the windows icon tray, and click 'Change Date Time settings'.  A window should pop up, and somewhere on there you should be able to pick an Internet Time server (NTP) to synchronize with.

Lastly, I've seen this sort of behavior a long time ago, and the only fix that was found at the time was to delete the ACT configuration files, which also unfortunately contain all your spell timers / triggers.  These files can be found by going to the ACT About tab and clicking the 'App Data Folder' button.  In there is a folder named Config, which contains both the FFXIV Plugin and the global ACT config files.  Close ACT completely, rename/delete this folder, and then reopen ACT / reinstall the plugin.

**Comment by Corrupt1on** [comment]
Hello, I posted this before that was suggested to me but that did fix the issue. Seems to be Guild Work beta effecting the chat time or whatever exactly was suggested. Works now thanks for all you do!
