### ISSUE TITLE
weird error 

### ISSUE THREAD

**Issue by dropme1** [ravahn/FFXIV_ACT_Plugin#30]
![](http://puu.sh/iMefC/6b53b023f9.png)

getting this error

im using latest version of ACT and rainbowmage overplay plugin

Ive been having this error ever since I used this but parse seemed working so I didnt really care
but Im worried that this might have affect on parse. 
What does this error mean and how do I fix it?

**Comment by ravahn** [comment]
Last10DPS is the name of the column which shows the average dps over the last 10 seconds.

The 'Collection was modified' is usually due to multi-threading problems -  one thread is trying to read a collection of data, while another thread modifies that collection.

This error should not affect the parser accuracy.

I'll see if I can find a solution, there are some hints about avoiding enumerators using the .ToList() extension method.

**Comment by dropme1** [comment]
thanks

**Comment by ravahn** [comment]
I included a first attempt at a fix for this.  Can you let me know if you still have the problem after v1.4.1.0?
