### ISSUE TITLE
No data in main window

### ISSUE THREAD

**Issue by anooob** [ravahn/FFXIV_ACT_Plugin#319]
Im having issues with getting act to work. I am running act as administrator.
When I click test game connection it seems to work 
![image](https://github.com/ravahn/FFXIV_ACT_Plugin/assets/2974894/bb2fd160-ab52-4415-a4df-4393e580dd9d)
The header of program says log active 
![image](https://github.com/ravahn/FFXIV_ACT_Plugin/assets/2974894/3eab3a5c-5054-4670-9820-3bc646962193)
And I can see that it is actually writing data to the log file. But there is no data visible in the main window or overlay plugin.

**Comment by psolru** [comment]
Same here, running on Windows 11. Since the upgrade to the new OS version, it didn't work anymore.

Just tried this one and it worked for me: https://forums.advancedcombattracker.com/discussion/387/act-stops-showing-data

![NVIDIA_Share_hOKRIfJhAS](https://github.com/ravahn/FFXIV_ACT_Plugin/assets/47062395/f76d3e01-bcad-4b0e-95db-28d39024c1be)


I don't know if I have to do anything else, as the README of the plugin here links to the open-source-"Deucalion library"...

**Comment by anooob** [comment]
yep that worked
