### ISSUE TITLE
Aeolian Edge's potency not registered in potency parse

### ISSUE THREAD

**Issue by nobits9** [ravahn/FFXIV_ACT_Plugin#33]
The potency of Aeolian Edge is shown as blank in the potency parser. Please see screenshot
![image](https://cloud.githubusercontent.com/assets/7233503/8664615/8ceb618c-29a7-11e5-8125-415189164319.png)

**Comment by ravahn** [comment]
Yes, the 3.0 change to Aeolian Edge made calculating its potency much more complicated.  It has base potency of 100, rear potency of 180, combo potency (with gust slash) of 240, and rear combo potency of 360.  

I don't have any code currently which can distinguish between four different potency tiers.  I'll keep this open as an enhancement, but it will take a while to fix it.  I unfortunately can't just add a base value in there because it would cause issues for the DoT simulator - it shares the mapping to potency values to figure out a player's average damage per potency unit.

**Comment by nobits9** [comment]
That makes sense. Thanks for responding!

**Comment by ravahn** [comment]
I've decided not to continue working on potency parsing, other than the bare minimum to support the DPS simulation.  With 4.0 and a number of new features which affect potency (including gauges), this feature has become less accurate and I dont see a way to improve it.  Future game data changes may make it easier.
