### ISSUE TITLE
DoTs not displaying 

### ISSUE THREAD

**Issue by rmelcer** [ravahn/FFXIV_ACT_Plugin#47]
I saw in #46 that network parsing should be working 100% again, but only the initial DoT tick is being displayed in the main interface. The other DoT ticks are displayed in the logs when I select 'View Logs' on the encounter, however. If you look at the linked album, you'll see that my total damage was 2200 according to the main interface, but the logs see 4K+ with the rest of the ticks.

I haven't changed anything since 3.1 except updating the FFXIV plugin to 1.4.2.3, but willing to check any settings you want.

Pics: http://imgur.com/a/61KbI

**Comment by ravahn** [comment]
Can you email me logs of this happening to ravahn (at) hotmail.com?  Memory mode still needs an update for DoTs to work, but network mode works fine.

**Comment by rmelcer** [comment]
Sent

**Comment by ravahn** [comment]
Thanks!  When I import the act.log file, I see the DoT ticks simulated properly, and they are for approximately the correct amount.  However, it is clear from your screenshot that it is not working.

What happens if you go to the ACT Import/Export tab and import the act.log file - does it show the DoTs correctly?

Does this happen everywhere, or just on the striking dummy?

**Comment by rmelcer** [comment]
This was happening everywhere but uninstalling and installing ACT fixed it for me. Sorry for the noise!
