### ISSUE TITLE
Overheal value ERROR in 64bit Damage ACT

### ISSUE THREAD

**Issue by Squall-Leonhart** [ravahn/FFXIV_ACT_Plugin#55]
As title, the overheal value is broken in the plugin for the new version of ACT.

**Comment by ravahn** [comment]
Thanks for the report.  This is odd - it happens for me as well with my compiled DLL, but doesn't happen while debugging the same code.  From the stack trace I see it is trying to implicitly convert a Dnum into an Int32 which is impossible due to the new update, so I have modified the code that calculates all damage/heal sums / percents to use Int64 explicitly.  Will go out in v1.4.2.15 soon.

**Comment by Squall-Leonhart** [comment]
this seems to have resolved itself?
