### ISSUE TITLE
Question - ZYX Enemies Position

### ISSUE THREAD

**Issue by r4nm4** [ravahn/FFXIV_ACT_Plugin#71]
Dear Ravahn,
this is only a question and I really hope in your answer.
From your plugin regular log (no debug), is it possible to extract the enemies ZYX position?
Thank you so much for your awesome job!
Cheers

**Comment by ravahn** [comment]
Possibly.  Position is logged on each combat hit (message type 21)  after the enemy's Current+Max HP/MP/TP. Since Max TP is 1000, it should be pretty easy to find the position - I believe the order is X|Y|Z.  

The position is not logged on enemies when they first appear, though.

Also, the plugin does not report the position of players or enemies periodically, so there is no way to detect in-game motion unless some combat action is taken by the enemy.

**Comment by r4nm4** [comment]
Dear Ravahn,
first of all thank you so much for your answer.
Yeah, I saw that but I tried to ask to maximum expert in this topic :)
Thank you again fro your amazing work.
Cheers
