### ISSUE TITLE
v1.5.1.0 Crit% missing?

### ISSUE THREAD

**Issue by Mitsuma** [ravahn/FFXIV_ACT_Plugin#76]
So with the direct hit percentage shows fine but crit percentage got replaced by crit types.
Those always say 0%. 
Crit% itself seems to work, as it shows on my old overlay still, it just doesn't seem to appear on the main window.
![advanced combat tracker_2017-06-21_19-19-19](https://user-images.githubusercontent.com/8568089/27397537-f0af2cb0-56b6-11e7-8b30-4d56e017b5e8.jpg)

On that note what are those crit types supposed to mean? I supposed only crit, only direct hit and both?
I also looked into the Options under Encounter View Options, no "Crit%" option there.
![advanced combat tracker_2017-06-21_19-23-26](https://user-images.githubusercontent.com/8568089/27397585-2a46aa66-56b7-11e7-97ee-35d817c7ba70.jpg)
Unsure if it is a bug or just me.

On a slightly offtopic note but related to this, I want to fix my overlay but I'm not sure what variables the new things use. As an example this is what the rainbowmage based one uses right now for crit.
`{ text: "{crithit%}", width: "", align: "center" },`
I haven't tried to figure it on my own yet, is it just "directhit%"? If we can show the mixed ones what are the variables for that.
Sorry if that part has nothing to do with the plugin itself, not sure where else to ask.

**Comment by ravahn** [comment]
Good catch, I suspect this is due to changes in EQ2 so Aditu changed the default Crit column.  I'll try to fix this in the next update.

**Comment by ravahn** [comment]
In reviewing the settings, I think Aditu (creator of ACT) changed it to show the 'CritTypes' column by default due to changes to Everquest2.  The more interesting columns are CritDam%/CritHeal%.  Try turning these on and see if it solves the problem.

It doesn't look like i can change the columns to be by default visible without removing/re-adding, but I am hesitant to do that since they are default ACT columns.

Regarding your second question, prior to the most recent update, Direct Hit was not available to overlays.  I added two variables = {DirectHitPct} and {CritDirectHitPct}, so you can use those.   in general, you can find a list of all available variables by going to Options -> Mini Parse Window, and click the "Add Preset" button.   you can find the correct syntax for each variable by finding it in the list, and adding it to the per-combat formatting.

**Comment by Mitsuma** [comment]
Thank you for your reply.
I can confirm that CritDam% is indeed what was named Crit% before.
![2017-06-22_19-40-35](https://user-images.githubusercontent.com/8568089/27447785-b03951fc-5782-11e7-8706-635dd0003cbb.jpg)
(My rainbowmage overlay and the CritDmg% in ACT window.
CritHeal% seems to be, as the name implies, only for DPS. 

I can also confirm that the new variables work fine.
![ffxiv_dx11_2017-06-22_19-46-23](https://user-images.githubusercontent.com/8568089/27448039-894236bc-5783-11e7-98d2-690eb3dde44d.jpg)
